# Generated by Django 5.1.5 on 2025-02-01 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faqsapp', '0002_alter_faq_options_faq_answer_bn_faq_answer_hi_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={},
        ),
        migrations.RemoveField(
            model_name='faq',
            name='answer_bn',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='answer_hi',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='question_bn',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='question_hi',
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_translated',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_translated',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
